### PR TITLE
Feat/show more data

### PR DESCRIPTION
**Pull request by msadura**
Paginating displayed data in table rows / kanban boards. 
https://app.charmverse.io/charmverse/page-3431887540171268

Screenshot 2023-02-15 at 17 12 00
Screenshot 2023-02-15 at 17 11 51
Screenshot 2023-02-15 at 17 11 43

### CODE REVIEW

**Comment by msadura** [comment]
EDIT: updated UI to be more notion-like

**Review by mattcasey — CHANGES_REQUESTED** [review]
There is a bug that the 'load more' action gets triggered when i am just setting the page size - or even if i change my mind, it triggers when i close the page size menu. I wanted to change page size to 10 from 100 and couldn't figure out why it wasn't going to 10 :)

**Comment by mattcasey** [comment]
FYI the initial idea was going to be to save the page size to the view, the way Notion does, and have it in the View settings as well the way Notion does. But I actually think this maybe fine for now. Just want to bring it up to Chris.

**Comment by mattcasey** [comment]
> I actually was not sure how we want to "save" that - in db? Local storage? Is it per page setting or global for board / table?

I think its for everyone, similar to how we store view filters, etc. for now. I think Notion does it that way,  since it's part of view settings. for that it would just be adding another value  to block.fields on the 'view block'

**Review by mattcasey — APPROVED** [review]

**Pull request merged**
