### PR TITLE
Revert domain name of a space

### PR DESCRIPTION
**Pull request by valentinludu**
This migration file will rename a specific user's domain name back to what it was.

### CODE REVIEW

**Review by Devorein — APPROVED** [review]

**Review by msadura — CHANGES_REQUESTED** [review]
Honestly I do not feel like this script should belong to migration scripts. 
As far as I understand migrations scripts it is about changing db structure and adapting fields. This one is just a specific operation for specific user.
I do not see a reason for committing id and name of our user to our codebase. If you think this script can be useful for the future I would just name it "changeSpaceDomain", place it directly in scripts + remove user-specidfic data.

**Comment by motechFR** [comment]
+1 on Marek's comment. It's important to not commit any PRs with actual UUIDs or domains.

In terms of the migration, this script is a one-off support task, so it belongs in scripts.

**Comment by motechFR** [comment]
Santisation of the script:

amend data and then recommit witgh


git commit --amend -m "Update script"

git push --force

**Comment by valentinludu** [comment]
Opened a PR to validate with the team.
Will run this locally. 
Closing this.

**Pull request closed without merging**
