### PR TITLE
Fix history bug when updating URLs outside of Next.js rendering

### PR DESCRIPTION
**Pull request by mattcasey**
This also updates the URL when viewing a proposal, allowing the user to reload the page and still see it in the modal.

Cleanup:
- moved lib/browser.ts into lib/utilities/browser.ts

Tested:
- Discord import roles
- Database cards
- Bounties page
- Proposals page

### CODE REVIEW

**Comment by Devorein** [comment]
All the above test cases worked except for one
1. Try creating a bounty. The URL should have `bountyId` query params
2. Now click outside the modal to close it. The query params `bountyId` is still there

**Review by Devorein — APPROVED** [review]

**Review by Devorein — CHANGES_REQUESTED** [review]
All the above test cases worked except for one.

1. Try creating a bounty or a proposal. The URL should have bountyId or id query params
2. Now click outside the modal to close it. The query params bountyId/id is still there

**Comment by Devorein** [comment]
Updates: I've also pushed a new commit that updates the URL when creating/editing/opening/closing a proposal template.

**Review by Devorein — APPROVED** [review]

**Comment by mattcasey** [comment]
thanks @Devorein

**Pull request merged**
