### PR TITLE
Arrange toggle arrow on a page

### PR DESCRIPTION
**Pull request by valentinludu**
Toggle arrow was jumping to each line instead of staying on the first line when a toggle is created in a page.

https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=86f54ac9-07fc-4d87-8452-1bdcca7e033c

### CODE REVIEW

**Comment by motechFR** [comment]
Hey @valentinludu 

I tried making a very long line of content and this happened (offset of cursor). Is this the original issue, or something else?

image

**Comment by valentinludu** [comment]
> Hey @valentinludu
> 
> I tried making a very long line of content and this happened (offset of cursor). Is this the original issue, or something else?
> 
> image

Oh, I see. I will make a fix first thing tomorrow morning.

The original issue was different. That arrow icon was way off in the left.

**Review by motechFR — APPROVED** [review]

**Comment by motechFR** [comment]
> > Hey @valentinludu
> > I tried making a very long line of content and this happened (offset of cursor). Is this the original issue, or something else?
> > image
> 
> Oh, I see. I will make a fix first thing tomorrow morning.
> 
> The original issue was different. That arrow icon was way off in the left.

Great, thanks for letting me know

**Comment by valentinludu** [comment]
> > Oh, I see. I will make a fix first thing tomorrow morning.
> > The original issue was different. That arrow icon was way off in the left.
> 
> Great, thanks for letting me know

Done

**Pull request merged**
